language: java
jdk:
- oraclejdk8
# No more jdk7

# We used IntelliJ IDEA to fix problems 
notifications:
  hipchat:
    rooms:
      secure: THeVKnnAhencuR03zX8JVlzqDPWiH98XACdz2VXd285qrVhAr7iSi/hBXCyLWOxPdl+G2Lu0TIFfOWyMNTgItg/U9Vzit3mAoULz6ony/I7lN0WH5HUrOeys61eWR+FItNgtosT1At8niR9pP+/IZKq1OBEwnViGhhzS1BbWG4U=
