# TowerWarZ Config Default
# Created 25/3/16 7:07 SST

# Config version. Touching will result in your config being overriden by defaults
config-version: 1.0

# The global server of TowerWarZ.
universal-multiplayer-server: "multiplay.towerwarz.net"

# The version of the game
game-version: InDev

# ModLoader
twz-ml:
  enable-ml: true # Enable the modloader?
  ml-mods-dir: "%APPDATA%\TowerWarZ\mods" # Mods directory. Change if you're on windows
